---
title: "Movies & Me"
author: "Mickaël Canouil, *Ph.D.*"
date: '`r format(Sys.time(), "%d %B %Y")`'
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    theme: cerulean
    social: [ "twitter", "facebook" ]
    source_code: "https://github.com/mcanouil/IMDbRating"
    fig_width: 12
    fig_height: 5
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
options(stringsAsFactors = FALSE)
fig_params <- list(
  res = 300,
  width = 12,
  height = 5
)

### Define
n_cores <- parallel::detectCores()

### Load packages
library(tidyverse)
library(viridis)
library(scales)
library(lubridate)
library(grid)
library(gridExtra)
library(ggrepel)
library(ggpubr)
library(rvest)
library(gganimate)
library(flexdashboard)

source("https://github.com/mcanouil/DEV/raw/master/R/theme_black.R")
source("https://github.com/mcanouil/DEV/raw/master/R/format.R")

base_family <- "" # if ("sysfonts" %in% installed.packages()) "xkcd" else ""
theme_set(theme_black(base_size = 9, base_family = base_family))
knitr::opts_chunk$set(autodep = TRUE, cache = TRUE)
```

```{r movies_data, incude = FALSE}
raw_movies_theatres <- source("./data/movies_theatres.R")$value
all_movies_theatres <- raw_movies_theatres %>% 
  dplyr::mutate(
    Month = factor(Month, levels = readr::locale(date_names = "en")$date_names$mon)
  ) %>% 
  dplyr::filter(Year > 2013)
```

# My Life in a Movie Theatre

## Row {data-height=100}

### Movies Last Month

```{r}
last_month <- readr::locale(date_names = "en")$date_names$mon[lubridate::month(lubridate::today()) - 1]
last_month_year <- if ((lubridate::month(lubridate::today()) - 1) == 12) {
  lubridate::year(lubridate::today()) - 1
} else {
  lubridate::year(lubridate::today())
}
all_movies_theatres %>%
  dplyr::count(Year, Month, name = "Count") %>% 
  dplyr::filter(Year == lubridate::year(lubridate::today())) %>% 
  dplyr::filter(Month == last_month) %>% 
  .[["Count"]] %>% 
  flexdashboard::valueBox(
    caption = paste0("Movies last Month (", last_month, " ", last_month_year, ")"), 
    icon = "fa-film"
  )
```

### Movies per Month

```{r}
all_movies_theatres %>%
  dplyr::count(Year, Month, name = "Count") %>% 
  dplyr::summarise_at(
    .vars = dplyr::vars(Count),
    .funs = list(mean = ~mean(., na.rm = TRUE), sd = ~stats::sd(., na.rm = TRUE))
  ) %>% 
  dplyr::mutate_all(.funs = ~signif(.x, digits = 3)) %>% 
  dplyr::mutate(value = paste0(mean, " (±", sd, ")")) %>% 
  .[["value"]] %>% 
  flexdashboard::valueBox( icon = "fa-film")
```

### Movies per Year

```{r}
all_movies_theatres %>%
  dplyr::count(Year, name = "Count") %>% 
  dplyr::summarise_at(
    .vars = dplyr::vars(Count),
    .funs = list(mean = ~mean(., na.rm = TRUE), sd =  ~stats::sd(., na.rm = TRUE))
  ) %>% 
  dplyr::mutate_all(.funs = ~signif(.x, digits = 3)) %>% 
  dplyr::mutate(value = paste0(mean, " (±", sd, ")")) %>% 
  .[["value"]] %>% 
  flexdashboard::valueBox(icon = "fa-film")
```

## Row {data-height=900 data-width=100% .tabset .tabset-fade}

### Movies in Theatres (Count)

```{r}
p <- all_movies_theatres %>%
  dplyr::count(Year, Month, name = "Count") %>% 
  dplyr::mutate(Month_int = as.numeric(Month)) %>% 
  ggplot2::ggplot(
    mapping = ggplot2::aes(
      x = Month_int, 
      y = Count, 
      fill = factor(Year),
      colour = factor(Year)
    )
  ) +
  # ggplot2::geom_smooth(
  #   mapping = ggplot2::aes(x = Month_int, y = Count, alpha = "Loess", linetype = "Loess"), 
  #   method = "loess", 
  #   inherit.aes = FALSE,
  #   se = FALSE,
  #   key_glyph = "timeseries"
  # ) +
  ggplot2::geom_line(
    data = ~dplyr::filter(.x, Year != lubridate::year(lubridate::today())), 
    key_glyph = "timeseries"
  ) +
  ggplot2::geom_point(
    data = ~dplyr::filter(.x, Year != lubridate::year(lubridate::today())), 
    mapping = ggplot2::aes(size = factor(Year)),
    na.rm = TRUE, 
    shape = 21, 
    colour = ggplot2::theme_get()$text$colour,
    show.legend = FALSE
  ) +
  ggplot2::geom_line(
    data = ~dplyr::filter(.x, Year == lubridate::year(lubridate::today())), 
    key_glyph = "timeseries"
  ) +
  ggplot2::geom_point(
    data = ~dplyr::filter(.x, Year == lubridate::year(lubridate::today())), 
    mapping = ggplot2::aes(size = factor(Year)),
    na.rm = TRUE, 
    shape = 21, 
    colour = ggplot2::theme_get()$text$colour,
    show.legend = FALSE
  ) +
  # ggplot2::geom_label(
  #   data = ~dplyr::filter(.x, Year == lubridate::year(lubridate::today())), 
  #   mapping = ggplot2::aes(label = Year),
  #   nudge_x = 1, 
  #   colour = ggplot2::theme_get()$plot.background$colour,
  #   show.legend = FALSE
  # ) +
  ggplot2::scale_x_continuous(
    breaks = seq_len(12), 
    labels = readr::locale()$date_names$mon
  ) +
  ggplot2::geom_label(
    data = ~dplyr::filter(.x, Count == min(Count)),
    mapping = ggplot2::aes(label = Count),
    nudge_y = -1, 
    colour = ggplot2::theme_get()$text$colour,
    fill = ggplot2::theme_get()$plot.background$colour,
    show.legend = FALSE
  ) +
  ggplot2::geom_label(
    data = ~dplyr::filter(.x, Count == max(Count)),
    mapping = ggplot2::aes(label = Count),
    nudge_y = 1, 
    colour = ggplot2::theme_get()$text$colour,
    fill = ggplot2::theme_get()$plot.background$colour,
    show.legend = FALSE
  ) +
  ggplot2::scale_y_continuous(limits = c(0, NA)) +
  ggplot2::scale_colour_viridis_d(begin = 0.4) +
  ggplot2::scale_fill_viridis_d(begin = 0.4) +
  ggplot2::scale_size_manual(
    values = c(rep(1, length(unique(all_movies_theatres[["Year"]])) - 1), 3) * 2
  ) +
  # ggplot2::scale_alpha_manual(name = NULL, values = 1) +
  # ggplot2::scale_linetype_manual(name = NULL, values = 2, guide = "none") +
  ggplot2::labs(x = NULL, y = "# Movies in Theatres", colour = "Year", fill = "Year") +
  ggplot2::theme(
    axis.text.x = ggplot2::element_text(angle = 45, vjust = 1, hjust = 1),
    axis.title = ggplot2::element_blank(),
    axis.ticks = ggplot2::element_blank(),
    axis.line = ggplot2::element_blank(),
    panel.grid.minor.x = ggplot2::element_blank(), 
    panel.border = ggplot2::element_blank(),
    plot.caption = ggplot2::element_text(size = 10, hjust = 0.5),
    plot.title = ggplot2::element_text(hjust = 0.5),
    plot.subtitle = ggplot2::element_text(hjust = 0.5)
  ) +
  gganimate::transition_reveal(
    along = Month_int, 
    range = c(1, 13), 
    keep_last = TRUE
  )

gganimate::animate(
  plot = p,
  width = fig_params[["width"]],
  height = fig_params[["height"]],
  units = "in", 
  res = fig_params[["res"]],
  bg = ggplot2::theme_get()$plot.background$colour,
  renderer = gganimate::gifski_renderer()
)
```

### Movies in Theatres (Cumulative Count)

```{r}
p <- all_movies_theatres %>% 
  dplyr::count(Year, Month, name = "Count") %>% 
  dplyr::mutate(Month_int = as.numeric(Month)) %>% 
  dplyr::arrange(Year, Month) %>% 
  dplyr::group_by(Year) %>% 
  dplyr::mutate(Count = cumsum(Count)) %>% 
  dplyr::ungroup() %>% 
  ggplot2::ggplot(
    mapping = ggplot2::aes(
      x = Month_int, 
      y = Count, 
      fill = factor(Year),
      colour = factor(Year)
    )
  ) +
  # ggplot2::geom_smooth(
  #   mapping = ggplot2::aes(x = Month_int, y = Count, alpha = "Loess", linetype = "Loess"), 
  #   method = "loess", 
  #   inherit.aes = FALSE,
  #   se = FALSE,
  #   key_glyph = "timeseries"
  # ) +
  ggplot2::geom_point(
    data = ~dplyr::filter(.x, Year != lubridate::year(lubridate::today())), 
    mapping = ggplot2::aes(size = factor(Year)),
    na.rm = TRUE,
    shape = 21,
    colour = ggplot2::theme_get()$text$colour,
    show.legend = FALSE
  ) +
  ggplot2::geom_line(
    data = ~dplyr::filter(.x, Year != lubridate::year(lubridate::today())), 
    key_glyph = "timeseries"
  ) +
  ggplot2::geom_point(
    data = ~dplyr::filter(.x, Year == lubridate::year(lubridate::today())), 
    mapping = ggplot2::aes(size = factor(Year)),
    na.rm = TRUE,
    shape = 21,
    colour = ggplot2::theme_get()$text$colour,
    show.legend = FALSE
  ) +
  ggplot2::geom_line(
    data = ~dplyr::filter(.x, Year == lubridate::year(lubridate::today())), 
    key_glyph = "timeseries"
  ) +
  ggplot2::scale_x_continuous(
    breaks = seq_len(12), 
    labels = readr::locale()$date_names$mon
  ) +
  ggplot2::scale_y_continuous(limits = c(0, NA)) +
  ggplot2::scale_colour_viridis_d(begin = 0.4) +
  ggplot2::scale_fill_viridis_d(begin = 0.4) +
  ggplot2::scale_size_manual(
    values = c(rep(1, length(unique(all_movies_theatres[["Year"]])) - 1), 3) * 2
  ) +
  # ggplot2::scale_alpha_manual(name = NULL, values = 1) +
  # ggplot2::scale_linetype_manual(name = NULL, values = 2, guide = "none") +
  ggplot2::labs(x = NULL, y = "# Movies in Theatres", colour = "Year", fill = "Year") +
  ggplot2::theme(
    axis.text.x = ggplot2::element_text(angle = 45, vjust = 1, hjust = 1),
    axis.title = ggplot2::element_blank(),
    axis.ticks = ggplot2::element_blank(),
    axis.line = ggplot2::element_blank(),
    panel.grid.minor.x = ggplot2::element_blank(), 
    panel.border = ggplot2::element_blank(),
    plot.caption = ggplot2::element_text(size = 10, hjust = 0.5),
    plot.title = ggplot2::element_text(hjust = 0.5),
    plot.subtitle = ggplot2::element_text(hjust = 0.5)
  ) +
  gganimate::transition_reveal(
    along = Month_int, 
    range = c(1, 13), 
    keep_last = TRUE
  )

gganimate::animate(
  plot = p,
  width = fig_params[["width"]],
  height = fig_params[["height"]],
  units = "in", 
  res = fig_params[["res"]],
  bg = ggplot2::theme_get()$plot.background$colour,
  renderer = gganimate::gifski_renderer()
)
```


# IMDb Ratings {.hidden}

## Row {data-height=100}

### Movies Last Month

```{r}
```

### Movies per Month

```{r}
```

### Movies per Year

```{r}
```

## Row {data-height=900 data-width=100% .tabset .tabset-fade}

### Movies (Count)

```{r}
```

