---
title: "My IMDb Ratings Analysis"
params:
  output_code: FALSE
  n_cores: !r parallel::detectCores()
  theme_dark: TRUE
  dpi: 150
  gg_fontsize: 9
output:
  html_document:
    theme: simplex
    fig_width: 5
    fig_height: 3.5
    self_contained: false
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE, echo = FALSE}
options(stringsAsFactors = FALSE)

knitr::opts_chunk$set(
  results = "asis",
  size = "small",
  include = TRUE, # params$output_code,
  echo = params$output_code,
  warning = params$output_code,
  message = params$output_code,
  tidy = FALSE,
  crop = TRUE,
  autodep = TRUE,
  fig.align = "center",
  fig.pos = "H",
  dpi = params$dpi,
  fig.path = "./images/"
)


### Define
n_cores <- params$n_cores

### Load packages
# library(parallel)
# library(kableExtra)
# library(Hmisc)
# library(broom)
# library(cowplot)

library(tidyverse)
library(viridis)
library(scales)
library(lubridate)
library(grid)
library(gridExtra)
library(ggrepel)
library(ggpubr)
library(rvest)
library(gganimate)

invisible(sapply(list.files("../DEV/Rfunctions/", full.names = TRUE), source))


### ggplot2 parameters
if (params$theme_dark) {
  theme_set(theme_black(base_size = params$gg_fontsize))
} else {
  theme_set(theme_grey(base_size = params$gg_fontsize))
}

### functions
set_colours <- function(fac, direction = 1) {
  fac %>% 
    unique() %>% 
    length() %>% 
    viridis_pal(direction = direction)(.) %>% 
    `names<-`(sort(unique(fac))) %>% 
    c("ALL" = ggplot2::theme_get()$text$colour, .)
}

best_streak <- function(vec) {
  bs <- function(vec) {
    rle(vec) %>% 
      unclass() %>% 
      as.data.frame() %>% 
      subset(values, lengths) %>% 
      max()
  }
  paste0(
    "Movies rated: ", sum(vec), "\n",
    "Best streak: ", bs(vec != 0), " days ! ",
    "Worst streak: ", bs(vec == 0), " days !"
  ) %>% 
    return()
}

get_metascore <- function(.x) { 
  sapply(.x, function(.y) {
    paste0(.y, "criticreviews") %>% 
    read_html() %>%
    html_node("div.metascore") %>%
    html_text() %>%
    as.numeric() %>% 
    `/`(10)
  })
}

plot_streak <- function(.data, facet = TRUE, number = TRUE) {
  .data <- .data %>%
    group_by(`Date Rated`) %>%
    summarise(
      avg_rating = mean(`Your Rating`),
      n_rating = n()
    ) %>%
    right_join(
      y = tibble(
        "Date Rated" = seq(
          from = as.Date(paste0(min(unique(year(.[["Date Rated"]]))), "-01-01")),
          to = as.Date(paste0(max(unique(year(.[["Date Rated"]]))), "-12-31")),
          by = 1
        )
      ),
      by = "Date Rated"
    ) %>%
    mutate(
      YearRated = year(`Date Rated`),
      Month = month(`Date Rated`, label = TRUE, abbr = FALSE),
      Day = day(`Date Rated`),
      wDay = wday(`Date Rated`, label = TRUE, abbr = FALSE, week_start = 1),
      wDay = factor(wDay, levels = rev(levels(wDay))),
      n_rating = ifelse(is.na(n_rating), 0, n_rating),
      Week = isoweek(`Date Rated`)
    ) %>%
    group_by(YearRated) %>%
    mutate(
      streak = paste0("[", year(`Date Rated`), "] ", best_streak(n_rating)),
      Week = ifelse(Month=="January" & Week>=50, 0, Week),
      Week = ifelse(Month=="December" & Week<=40, max(Week)+1, Week) 
    ) %>%
    ungroup()
  
  x_labels <- .data %>% 
    select(Week, Month) %>% 
    distinct() %>% 
    group_by(Month) %>% 
    summarise(Week = min(Week))

  p_out <- ggplot(
    data = .data, 
    mapping = aes(x = Week, y = wDay, fill = avg_rating, label = n_rating)
  ) +
    geom_tile(colour = "white", size = 0.1) +
    scale_fill_viridis_c(
      name = "Average\nRating", 
      limits = c(0, 10), 
      na.value = ggplot2::theme_get()$panel.background$fill
    ) +
    scale_y_discrete(expand = c(0, 0)) +
    scale_x_continuous(
      expand = c(0, 0), 
      breaks = x_labels[["Week"]], 
      labels = x_labels[["Month"]]
    ) +
    theme(
      axis.ticks = element_blank(),
      axis.text.x = element_text(angle = 45, hjust = 1),
      axis.title = element_blank(),
      panel.grid = element_blank()
    ) +
    labs(title = "Movies Streak", x = "Month", y = "Day")
  
  if (number) {
    p_out <- p_out + geom_text(colour = "white", fontface = "bold", size = 2)
  }
  if (facet) {
    p_out <- p_out + facet_grid(~streak)
  }
  return(p_out)
}

plot_genres_distribution <- function(.data) {
  .data %>% 
    mutate(
      Genre_details = map(Genres, function(x) {
        tibble(
          Genre = unique(unlist(strsplit(x, split = ", "))),
          Weight = 1 / length(Genre)
        )
      })
    ) %>% 
    unnest(Genre_details) %>% 
    group_by(Genre) %>% 
    summarise(Score = sum(Weight)) %>% 
    arrange(desc(Score)) %>% 
    filter(Genre!="NANA") %>% 
    mutate(
      Genre_label = Score>=quantile(Score, probs = 2/3),
      Genre_label = ifelse(Genre_label, Genre, NA),
      Genre = factor(Genre, levels = unique(Genre))
    ) %>% 
    ggplot(aes(x = factor(1), y = Score, fill = Genre)) +
      geom_bar(colour = "white", width = 1, stat = "identity") +
      geom_label_repel(
        aes(
          x = 1.5,
          y = cumsum(rev(Score)) - rev(Score) / 2,
          label = rev(Genre_label)
        ), 
        fill = "white", 
        size = 2, 
        nudge_x = 0.25,
        min.segment.length = 0, 
        segment.colour = ggplot2::theme_get()$line$colour
      ) +
      coord_polar(theta = "y") +
      scale_fill_viridis_d(guide = guide_legend(ncol = 2)) +
      labs(title = "Distribution of Genres") +
      theme(
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        panel.grid = element_blank(),
        panel.border = element_blank(), 
        legend.text = element_text(size = rel(0.4))
      )
}

plot_genres_rating <- function(.data) {
  .data %>% 
    mutate(
      Genre_details = map(Genres, function(x) {
        tibble(
          Genre = unique(unlist(strsplit(x, split = ", "))),
          Weight = 1 / length(Genre)
        )
      })
    ) %>% 
    unnest(Genre_details) %>% 
    group_by(Genre) %>% 
    summarise(
      Score = sum(Weight),
      Rating = (Weight %*% `Your Rating`) / Score,
      Rating_avg = mean(`Your Rating`),
      N = n()
    ) %>% 
    mutate(
      Per = N / sum(N)
    ) %>% 
    arrange(desc(Rating)) %>% 
    filter(Genre!="NANA") %>% 
    mutate(
      Genre = factor(Genre, levels = unique(Genre))
    ) %>% 
    ggplot(aes(x = Genre, y = Rating, fill = N)) +
      geom_bar(width = 1, stat = "identity", colour = "white") +
      geom_text(aes(label = N), colour = ggplot2::theme_get()$panel.grid$colour, nudge_y = -0.5, size = 2) +
      geom_text(aes(label = round(Rating, digits = 2)), colour = ggplot2::theme_get()$text$colour, nudge_y = 0.5, size = 3) +
      scale_fill_viridis_c(direction = 1) +
      scale_x_discrete(expand = c(0, 0)) +
      scale_y_continuous(expand = c(0, 0), limits = c(0, 10), breaks = seq(0, 10, 2)) +
      labs(title = "Average Weighted Rating per Genre", fill = "# Movies") +
      theme(
        axis.text.x = element_text(angle = 45, hjust = 1),
        axis.title.x = element_blank(),
        panel.grid.major.x = element_blank()
      )
}

plot_ratings_runtime <- function(.data) {
  .data %>% 
    select(`Your Rating`, `Runtime (mins)`) %>%
    group_by(`Your Rating`) %>%
    summarise(Runtime = sum(`Runtime (mins)`, na.rm = TRUE) / (60 * 24)) %>%
    ggplot(aes(x = factor(1), y = Runtime, fill = factor(`Your Rating`))) +
      geom_bar(colour = "white", width = 1, stat = "identity") +
      geom_label_repel(
        aes(
          x = 1.5,
          y = cumsum(rev(Runtime)) - rev(Runtime) / 2,
          label = round(rev(Runtime), digits = 1)
        ), 
        fill = "white", 
        size = 2, 
        nudge_x = 0.25,
        min.segment.length = 0, 
        segment.colour = "white"
      ) +
      coord_polar(theta = "y") +
      scale_fill_viridis_d(name = "Rating") +
      labs(title = "Days Spent per Rating") +
      theme(
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        axis.title = element_blank(),
        panel.grid = element_blank(),
        panel.border = element_blank()
      )
}

plot_ratings_distribution <- function(.data) {
  
  data_ratings <- full_join(
    x = .data %>% 
      select(ends_with("Rating"), YearRated) %>%
      gather(key = Who, value = Rating, -YearRated) %>%
      mutate(
        Who = Who %>% gsub(" Rating", "", .) %>% gsub("Your", "User", .),
        rounded_rating = round(Rating, digits = 0)
      ) %>% 
      select(-Rating) %>% 
      group_by(YearRated, Who, rounded_rating) %>% 
      summarise(n = n()) %>% 
      mutate(rating = factor(x = rounded_rating, levels = 1:10)) %>% 
      complete(rating) %>% 
      mutate(
        rounded_rating = ifelse(is.na(rounded_rating), as.numeric(rating), rounded_rating),
        n = ifelse(is.na(n), 0, n)
      ) %>% 
      ungroup() %>% 
      group_by(YearRated, Who) %>% 
      mutate(
        total = sum(n),
        ntotal = n/total
      ) %>% 
      ungroup() %>% 
      select(YearRated, Who, rounded_rating, ntotal),
    y = .data %>% 
      select(ends_with("Rating"), YearRated) %>%
      gather(key = Who, value = Rating, -YearRated) %>%
      mutate(
        Who = Who %>% gsub(" Rating", "", .) %>% gsub("Your", "User", .),
        rounded_rating = round(Rating, digits = 0)
      ) %>% 
      select(-Rating),
    by = c("YearRated", "Who", "rounded_rating")
  )
  
  ggplot(data = data_ratings, aes(x = rounded_rating, fill = Who)) +
    geom_density(colour = "white", adjust = 2.5, alpha = 0.25) +
    geom_histogram(
      data = distinct(data_ratings),
      aes(y = ntotal),
      stat = "identity",
      binwidth = 0.5,
      colour = "white",
      position = position_dodge(preserve = "single")
    ) +
    scale_x_continuous(
      expand = c(0, 0), 
      name = "Rating", 
      limits = c(0, 10), 
      breaks = c(0, seq_len(10))
    ) +
    scale_y_continuous(expand = c(0, 0), labels = percent, limits = c(0, 0.5)) +
    scale_fill_viridis_d() +
    labs(
      x = "Rating", 
      y = "Proportion", 
      title = "Distribution of Ratings", 
      fill = "Rating from"
    )
}

plot_bad <- function(.data, n = 3, gg_fontsize = params$gg_fontsize) {
  .data %>% 
    arrange(`Your Rating`, `IMDb Rating`) %>%
    select(Title, `Your Rating`, `IMDb Rating`) %>%
    head(n) %>%
    ggtexttable(rows = NULL, theme = ttheme("mBlack", base_size = gg_fontsize*0.80)) %>%
    arrangeGrob(
      top = text_grob("Worst Movies", color = ggplot2::theme_get()$text$colour, face = "bold", size = gg_fontsize*1.2)
    ) %>% 
    as_ggplot()
}
  
plot_top <- function(.data, n = 3, gg_fontsize = params$gg_fontsize) {
  .data %>% 
    arrange(desc(`Your Rating`), desc(`IMDb Rating`)) %>%
    select(Title, `Your Rating`, `IMDb Rating`) %>%
    head(n) %>%
    ggtexttable(rows = NULL, theme = ttheme("mBlack", base_size = gg_fontsize*0.80)) %>%
    arrangeGrob(
      top = text_grob("Best Movies", color = ggplot2::theme_get()$text$colour, face = "bold", size = gg_fontsize*1.2)
    ) %>% 
    as_ggplot()
}

plot_movies_theatres <- function(.year, .data) {
  .data %>% 
    mutate(
      Month = factor(Month, levels = levels(month_factor)),
      size = Year==.year
    ) %>% 
    ggplot() +
      geom_hline(yintercept = seq(0, 20, by = 2.5), colour = "white", size = 0.10) +
      geom_hline(yintercept = seq(0, 15, by = 5), colour = "white", size = 0.2) +
      geom_rect(fill = ggplot2::theme_get()$panel.background$fill, xmin = 1, xmax = 0, ymin = 0, ymax = 20) +
      geom_hline(yintercept = 20, colour = "white", size = 0.2) +
      geom_vline(aes(xintercept = as.integer(Month)), colour = "white", size = 0.1) +
      geom_text(
        data = tibble(
          Count = c(0, rep(seq(5, 20, by = 5), times = 4)), 
          Month = c(1, rep(c(1, 4, 7, 10), each = 4))
        ),
        aes(x = Month, y = Count, label = Count),
        colour = ggplot2::theme_get()$text$colour,
        size = 2.5
      ) +
      geom_smooth(
        aes(x = as.integer(Month), y = Count, colour = "ALL"),
        method = "loess",
        se = FALSE,
        size = 1,
        linetype = 2,
        show.legend = TRUE
      ) +
      geom_point(
        aes(
          x = as.integer(Month),
          y = Count,
          colour = factor(Year),
          size = size
        ),
        shape = 21
      ) +
      geom_line(
        aes(
          x = as.integer(Month),
          y = Count,
          group = Year,
          colour = factor(Year),
          size = size
        )
      ) +
      scale_colour_manual(
        name = "Year", 
        values = set_colours(.data[["Year"]])
      ) +
      scale_size_manual(values = c(0.15, 0.5)*1.5, guide = "none") +
      scale_y_continuous(limits = c(0, 22), expand = c(0, 0)) +
      scale_x_continuous(limits = c(0, 12), breaks = seq_len(12), labels = levels(month_factor)) +
      labs(title = "# Movies Seen in Theatres") +
      coord_polar(theta = "x", start = 2*pi * 22/24) +
      theme(
        axis.text.y = element_blank(),
        axis.text.x = element_text(size = rel(0.80)),
        axis.title = element_blank(),
        axis.ticks = element_blank(),
        axis.line = element_blank(),
        panel.grid = element_blank(),
        panel.border = element_blank()
      )
}

print_infography <- function(.x, .a, .b, .c, .d, .e, .g, .h, .i, gg_fontsize = params$gg_fontsize) {
  ggarrange(
    ggarrange(
      .b[[1]],
      ggarrange(
        .a[[1]],
        ggarrange(
          .i[[1]],
          ggarrange(.c[[1]], .d[[1]], ncol = 1, nrow = 2),
          ncol = 2,
          widths = c(0.6, 0.40)
        ),
        nrow = 2,
        align = "v"
      ),
      ncol = 2,
      align = "v",
      widths = c(1/3, 2/3)
    ),
    ggarrange(
      .e[[1]],
      .h[[1]] + 
        guides(fill = guide_legend(
          ncol = 1, 
          keyheight = unit(gg_fontsize*2/3, "pt"),
          keywidth = unit(gg_fontsize, "pt")
        )), 
      .g[[1]] + 
        guides(fill = guide_legend(
          ncol = 1, 
          keyheight = unit(gg_fontsize*1.2, "pt"),
          keywidth = unit(gg_fontsize*1.2, "pt")
        )), 
      ncol = 3,
      align = "v",
      widths = c(0.5, 0.25, 0.25)
    ),
    nrow = 2,
    heights = c(2/3, 1/3),
    align = "v"
  ) %>%
    arrangeGrob(
      top = text_grob(
        paste0(.x, " in Movie Theatres"), 
        color = ggplot2::theme_get()$text$colour, 
        face = "bold", 
        size = 16
      ),
      left = "",
      right = "", 
      bottom = text_grob(
        "© Mickaël 'Coeos' Canouil", 
        color = ggplot2::theme_get()$text$colour, 
        face = "bold",
        hjust = -8.08,
        size = 5
      )
    ) %>%
    as_ggplot()
}
```

```{r movies_data, incude = FALSE}
### data
month_factor <- factor(locale()$date_names$mon, levels = locale()$date_names$mon)
movies_theatres <- tribble(
  ~Year, ~Month, ~Count,
  2013, "January", NA,
  2013, "February", NA,
  2013, "March", NA,
  2013, "April", 8,
  2013, "May", 10,
  2013, "June", 10,
  2013, "July", 10,
  2013, "August", 8,
  2013, "September", 9,
  2013, "October", 6,
  2013, "November", 10,
  2013, "December", 10,
  2014, "January", 14,
  2014, "February", 13,
  2014, "March", 15,
  2014, "April", 12,
  2014, "May", 9,
  2014, "June", 6,
  2014, "July", 4,
  2014, "August", 14,
  2014, "September", 5,
  2014, "October", 20,
  2014, "November", 13,
  2014, "December", 7,
  2015, "January", 7,
  2015, "February", 14,
  2015, "March", 10,
  2015, "April", 9,
  2015, "May", 11,
  2015, "June", 6,
  2015, "July", 6,
  2015, "August", 10,
  2015, "September", 8,
  2015, "October", 13,
  2015, "November", 10,
  2015, "December", 9,
  2016, "January", 7,
  2016, "February", 17,
  2016, "March", 9,
  2016, "April", 8,
  2016, "May", 13,
  2016, "June", 8,
  2016, "July", 12,
  2016, "August", 14,
  2016, "September", 11,
  2016, "October", 12,
  2016, "November", 6,
  2016, "December", 18,
  2017, "January", 7,
  2017, "February", 8,
  2017, "March", 13,
  2017, "April", 15,
  2017, "May", 7,
  2017, "June", 9,
  2017, "July", 19,
  2017, "August", 10,
  2017, "September", 12,
  2017, "October", 13,
  2017, "November", 11,
  2017, "December", 17,
  2018, "January", 12,
  2018, "February", 10,
  2018, "March", 14,
  2018, "April", 14,
  2018, "May", 12,
  2018, "June", 14,
  2018, "July", 10,
  2018, "August", 14,
  2018, "September", 14,
  2018, "October", NA,
  2018, "November", NA,
  2018, "December", NA
)
```

```{r read_imdb, include = FALSE}
# "http://www.imdb.com/user/ur56341222/ratings?start=1&view=compact"

ratings_old <- read_csv("ratings_ms.csv")

ratings <- read_csv("ratings.csv", locale = locale(encoding = "Windows-1252")) %>%
  filter(!Const%in%ratings_old[["Const"]]) %>% 
  mutate(
    YearRated = year(`Date Rated`),
    Genres = map(Genres, simpleCap) %>%
      gsub("Musical", "Music", .)
  ) %>%
  filter(YearRated>=2016)

if (nrow(ratings)>0) {
  ratings <- ratings %>%
    mutate(
      `Metascore Rating` = get_metascore(URL)
    ) %>%
    bind_rows(ratings_old) %>%
    write_csv(path = "ratings_ms.csv")
} else {
  ratings <- read_csv("ratings_ms.csv")
}
```

# Infography {.tabset}
```{r ggplot_time, fig.height = 9, fig.width = 16}
### make plots
gg_ratings <- ratings %>% 
  mutate(YR = YearRated) %>% 
  group_by(YR) %>% 
  nest() %>% 
  mutate(
    p_movies_streak = map(.x = data, .f = plot_streak),
    p_genres_distribution = map(.x = data, .f = plot_genres_distribution),
    p_genres_rating = map(.x = data, .f = plot_genres_rating),
    p_ratings_runtime = map(.x = data, .f = plot_ratings_runtime),
    p_ratings_distribution = map(.x = data, .f = plot_ratings_distribution),
    p_bad = map(.x = data, .f = plot_bad),
    p_top = map(.x = data, .f = plot_top)
  ) %>% 
  mutate(
    data_agg = list(movies_theatres),
    p_movies_theatres = map2(.x = YR, .y = data_agg, .f = plot_movies_theatres)
  ) %>% 
  select(-data, -data_agg) %>%
  ungroup()

p <- gg_ratings %>% 
  group_by(YR) %>% 
  mutate(
    gg = map(
      .x = YR,
      .a = p_movies_streak,
      .b = p_movies_theatres,
      .c = p_top,
      .d = p_bad,
      .e = p_genres_rating,
      .g = p_ratings_runtime,
      .h = p_genres_distribution,
      .i = p_ratings_distribution,
      .f = print_infography
    ) %>% 
      map2(.x = YR, .y = ., .f = function(x, y) {
        ggsave(
          filename = paste0("./images/", x, "_Coeos_IMDb.png"),
          plot = y,
          width = 16,
          height = 9,
          dpi = 300
        )
        cat("\n\n")
        cat("##", YR, "  \n\n")
        print(y)
        cat("\n\n")
        return(y)
      })
  ) %>% 
  ungroup()
```

```{r}
set_colours <- function(fac, direction = 1) {
  out <- fac %>%
    as.character() %>% 
    unique() %>%
    length() %>%
    viridis_pal(direction = direction)(.) %>%
    `names<-`(sort(unique(as.character(fac)))) %>%
    c("SMOOTH" = "white", .)
  out["ALL"] <- "white"
  return(out)
}

data_radar <- movies_theatres  %>% 
  mutate(
    Year = as.character(Year),
    Month = factor(Month, levels = locale()$date_names$mon)
  ) %>% 
  bind_rows(
    movies_theatres  %>% 
      mutate(
        Year = as.character(Year),
        Month = factor(Month, levels = locale()$date_names$mon)
      ) %>% 
      group_by(Month) %>% 
      summarise(
        Year = "ALL",
        Count = floor(mean(Count, na.rm = TRUE))
      )
  ) %>% 
  arrange(Year, Month) %>%
  mutate(
    YM = paste0(Year, sprintf("%02d", as.numeric(Month))) %>% factor() %>% as.integer(),
    Year = factor(x = Year, levels = c(2013:2018, "ALL")),
    Month_int = as.integer(Month)
  )

p <- ggplot(data = data_radar) +
  # theme
  theme_black(base_size = 16) +
  geom_hline(
    yintercept = seq(0, 20, by = 2.5), 
    colour = ggplot2::theme_get()$panel.grid$colour, 
    size = 0.2
  ) +
  geom_hline(
    yintercept = seq(0, 20, by = 5), 
    colour = ggplot2::theme_get()$panel.grid$colour, 
    size = 0.4
  ) +
  geom_rect(
    fill = ggplot2::theme_get()$plot.background$colour, 
    xmin = 1, 
    xmax = 0, 
    ymin = 0, 
    ymax = 20, 
    inherit.aes = FALSE
  ) +
  geom_hline(
    yintercept = 20, 
    colour = ggplot2::theme_get()$panel.grid$colour, 
    size = 0.4
  ) +
  geom_vline(
    xintercept = seq_len(12), 
    colour = ggplot2::theme_get()$panel.grid$colour, 
    size = 0.2
  ) +
  geom_text(
    data = tibble(
      Count = c(0, rep(seq(5, 20, by = 5), times = 4)), 
      Month = c(1, rep(c(1, 4, 7, 10), each = 4))
    ),
    mapping = aes(x = Month, y = Count, label = Count),
    colour = ggplot2::theme_get()$text$colour,
    size = 16 * 1/5,
    inherit.aes = FALSE
  ) +
  scale_y_continuous(limits = c(0, 22), expand = c(0, 0)) +
  scale_x_continuous(
    limits = c(0, 12), 
    breaks = seq_len(12), 
    labels = locale()$date_names$mon
  ) +
  coord_polar(theta = "x", start = 2 * pi * 11/12) +
  theme(
    axis.text.y = element_blank(),
    axis.text.x = element_text(size = rel(0.80)),
    axis.title = element_blank(),
    axis.ticks = element_blank(),
    axis.line = element_blank(),
    panel.grid = element_blank(),
    panel.border = element_blank()
  ) +
  # real geom
  geom_smooth(
    aes(x = Month_int, y = Count, colour = "SMOOTH"),
    method = "loess",
    se = FALSE,
    size = 1,
    linetype = 2,
    show.legend = TRUE
  ) +
  scale_colour_manual(
    name = "Year",
    breaks = names(set_colours(data_radar[["Year"]], direction = 1)),
    values = set_colours(data_radar[["Year"]], direction = 1)
  ) +
  scale_fill_manual(
    name = "Year",
    breaks = names(set_colours(data_radar[["Year"]], direction = 1)),
    values = set_colours(data_radar[["Year"]], direction = 1)
  ) +
  geom_point(
    mapping = aes(x = Month_int, y = Count, colour = Year, fill = Year), 
    size = 3, shape = 21
  ) +
  geom_path(
    mapping = aes(x = Month_int, y = Count, colour = Year), 
    size = 1.5
  ) +
  guides(colour = "none", fill = "none") + 
  transition_states(
    Year,
    transition_length = 6,
    state_length = 8
  ) +
  enter_appear(early = TRUE) +
  exit_disappear(early = TRUE) +
  ease_aes('linear') +
  labs(title = "# Movies Seen in Theatres: {closest_state}") +
  labs(caption = "© Mickaël 'Coeos' Canouil") +
  theme(plot.caption = element_text(size = 8))


fac <- 1
animate(
  plot = p, 
  width = 500*fac, 
  height = 500*fac, 
  units = "px", 
  bg = ggplot2::theme_get()$plot.background$colour,
  renderer = gifski_renderer(
    file = "./images/Coeos_IMDb_01.gif"
  )
)


# knit_print.gganim(
#   x = p,
#   renderer = gifski_renderer(
#     file = "./images/Coeos_IMDb.gif",
#     width = 400*fac,
#     height = 400*fac,
#     bg = ggplot2::theme_get()$plot.background$colour
#   ),
#   device = "png",
#   width = 400*fac, 
#   height = 400*fac, 
#   units = "px",
#   bg = ggplot2::theme_get()$plot.background$colour
# )
```

```{r}
p <- ratings %>% 
  select(`Your Rating`, `Runtime (mins)`, YearRated) %>%
  group_by(YearRated, `Your Rating`) %>%
  summarise(Runtime = sum(`Runtime (mins)`, na.rm = TRUE) / (60 * 24)) %>% 
  mutate(
    `Your Rating` = factor(x = `Your Rating`, levels = 1:10)
  ) %>% 
  mutate(
    time = Runtime/sum(Runtime),
    label = as.character(round(rev(Runtime), digits = 1)),
    x = 1.5,
    y = cumsum(rev(time)) - rev(time) / 2
  ) %>% 
  complete(`Your Rating`) %>% 
  mutate(Runtime = replace_na(Runtime, 0)) %>% 
  ungroup() %>% 
  ggplot() +
    theme_black(base_size = 16) +
    geom_bar(
      mapping = aes(x = factor(1), y = time, fill = `Your Rating`), 
      colour = "white", 
      width = 1, 
      stat = "identity"
    ) +
    geom_label_repel(
      mapping = aes(x = x, y = y, label = label), 
      fill = "white",
      colour = "black",
      size = 16 * 1/2, 
      nudge_x = 0.25,
      min.segment.length = 0, 
      segment.colour = "white", 
      inherit.aes = FALSE
    ) +
    coord_polar(theta = "y") +
    scale_fill_viridis_d(name = "Rating") +
    labs(title = "Days Spent per Rating: {closest_state}") +
    theme(
      axis.ticks = element_blank(),
      axis.text = element_blank(),
      axis.title = element_blank(),
      panel.grid = element_blank(),
      panel.border = element_blank()
    ) +
    guides(fill = guide_legend(ncol = 2))  +
    transition_states(
      states = YearRated,
      transition_length = 4,
      state_length = 8
    ) +
    enter_appear() +
    exit_disappear() +
    ease_aes('linear')

fac <- 2
animate(
  plot = p, 
  width = 400*fac, 
  height = 400*fac, 
  units = "px", 
  bg = ggplot2::theme_get()$plot.background$colour,
  renderer = gifski_renderer(
    file = "./images/Coeos_IMDb_02.gif"
  )
)
```

```{r}
p <- plot_streak(.data = ratings, facet = FALSE, number = FALSE) +
  theme_black(base_size = 16) +
  coord_polar(theta = "x") +
  theme(
    axis.text.y = element_blank(),
    # axis.text.x = element_text(size = rel(0.80)),
    axis.title = element_blank(),
    axis.ticks = element_blank(),
    axis.line = element_blank(),
    panel.grid = element_blank(),
    panel.border = element_blank()
  ) +
  transition_states(
    states = YearRated,
    transition_length = 4,
    state_length = 8
  ) +
  enter_appear() +
  exit_disappear() +
  ease_aes('linear')

fac <- 2
animate(
  plot = p, 
  width = 400*fac, 
  height = 400*fac, 
  units = "px", 
  bg = ggplot2::theme_get()$plot.background$colour,
  renderer = gifski_renderer(
    file = "./images/Coeos_IMDb_03.gif"
  )
)
```

```{r}
data_ratings <- full_join(
  x = ratings %>% 
    select(ends_with("Rating"), YearRated) %>%
    gather(key = Who, value = Rating, -YearRated) %>%
    mutate(
      Who = Who %>% gsub(" Rating", "", .) %>% gsub("Your", "User", .),
      rounded_rating = round(Rating, digits = 0)
    ) %>% 
    select(-Rating) %>% 
    group_by(YearRated, Who, rounded_rating) %>% 
    summarise(n = n()) %>% 
    mutate(rating = factor(x = rounded_rating, levels = 1:10)) %>% 
    complete(rating) %>% 
    mutate(
      rounded_rating = ifelse(is.na(rounded_rating), as.numeric(rating), rounded_rating),
      n = ifelse(is.na(n), 0, n)
    ) %>% 
    ungroup() %>% 
    group_by(YearRated, Who) %>% 
    mutate(
      total = sum(n),
      ntotal = n/total
    ) %>% 
    ungroup() %>% 
    select(YearRated, Who, rounded_rating, ntotal),
  y = ratings %>% 
    select(ends_with("Rating"), YearRated) %>%
    gather(key = Who, value = Rating, -YearRated) %>%
    mutate(
      Who = Who %>% gsub(" Rating", "", .) %>% gsub("Your", "User", .),
      rounded_rating = round(Rating, digits = 0)
    ) %>% 
    select(-Rating),
  by = c("YearRated", "Who", "rounded_rating")
) %>% 
  mutate(
    YearRated = as.character(YearRated)
  ) %>% 
  bind_rows(
    full_join(
      x = ratings %>% 
        select(ends_with("Rating"), YearRated) %>%
        gather(key = Who, value = Rating, -YearRated) %>%
        mutate(
          Who = Who %>% gsub(" Rating", "", .) %>% gsub("Your", "User", .),
          rounded_rating = round(Rating, digits = 0)
        ) %>% 
        select(-Rating) %>% 
        group_by(Who, rounded_rating) %>% 
        summarise(n = n()) %>% 
        mutate(rating = factor(x = rounded_rating, levels = 1:10)) %>% 
        complete(rating) %>% 
        mutate(
          rounded_rating = ifelse(is.na(rounded_rating), as.numeric(rating), rounded_rating),
          n = ifelse(is.na(n), 0, n)
        ) %>% 
        ungroup() %>% 
        group_by(Who) %>% 
        mutate(
          total = sum(n),
          ntotal = n/total
        ) %>% 
        ungroup() %>% 
        mutate(YearRated = "ALL") %>% 
        select(YearRated, Who, rounded_rating, ntotal),
      y = ratings %>% 
        select(ends_with("Rating"), YearRated) %>%
        gather(key = Who, value = Rating, -YearRated) %>%
        mutate(
          Who = Who %>% gsub(" Rating", "", .) %>% gsub("Your", "User", .),
          rounded_rating = round(Rating, digits = 0)
        ) %>% 
        select(-Rating) %>% 
        mutate(YearRated = "ALL"),
      by = c("YearRated", "Who", "rounded_rating")
    )
  )


p <- ggplot(data = data_ratings, aes(x = rounded_rating, fill = Who)) +
  theme_black(base_size = 16) +
  geom_density(colour = "white", adjust = 2.5, alpha = 0.25) +
  geom_histogram(
    data = distinct(data_ratings),
    aes(y = ntotal),
    stat = "identity",
    binwidth = 0.5,
    colour = "white",
    position = position_dodge(preserve = "single")
  ) +
  scale_x_continuous(
    expand = c(0, 0), 
    name = "Rating", 
    limits = c(0, 10), 
    breaks = c(0, seq_len(10))
  ) +
  scale_y_continuous(expand = c(0, 0), labels = percent, limits = c(0, 0.5)) +
  scale_fill_viridis_d() +
  labs(
    x = "Rating", 
    y = "Proportion", 
    title = "Distribution of Ratings", 
    fill = "Rating from"
  ) + # facet_wrap(~YearRated)
  transition_states(
    YearRated,
    transition_length = 6,
    state_length = 8
  ) +
  enter_appear(early = TRUE) +
  exit_disappear(early = TRUE) +
  ease_aes('linear') +
  labs(
    title = "Distribution of Ratings: {closest_state}",
    caption = "© Mickaël 'Coeos' Canouil"
  ) +
  theme(
    plot.caption = element_text(size = 8),
    legend.position = c(1, 1),
    legend.justification = c(1.05, 1.05)
  )



fac <- 1
animate(
  plot = p, 
  width = 700*fac, 
  height = 500*fac, 
  units = "px", 
  bg = ggplot2::theme_get()$plot.background$colour,
  renderer = gifski_renderer(
    file = "./images/Coeos_IMDb_04.gif"
  )
)
```

