---
params:
  static: FALSE
title: "My IMDb Ratings Analysis"
author: "Mickaël Canouil, *Ph.D.*"
date: '`r format(Sys.time(), "%B %d, %Y")`'
knit: (function(inputFile, encoding) rmarkdown::render(inputFile, output_file = "index.html", encoding = encoding, output_dir = here::here("docs"), intermediates_dir = here::here("docs")))
output: 
  mctemplates::html_report: default
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    theme: cerulean
    social: [ "twitter", "facebook" ]
    source_code: "https://github.com/mcanouil/IMDbRating"
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
options("stringsAsFactors" = FALSE, "width" = 100)


### Load packages ==================================================================================
library(here)

suppressPackageStartupMessages({
  library(dplyr)
  library(tidyr)
  library(readr)
  library(purrr)
  library(sessioninfo)
  library(gt)
  library(lubridate)
  library(scales)
  library(ggplot2)
  library(gganimate)
  library(forcats)
  library(glue)
  library(stringr)
  library(ggtext)
  library(broom)
  library(rvest)
  library(xml2)
})


### Environment ====================================================================================
knitr::opts_chunk$set(
  comment = "#>",
  results = "asis",
  include = TRUE,
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  dpi = 120,
  tidy = FALSE,
  crop = TRUE,
  autodep = TRUE,
  fig.align = "center",
  fig.path = here("images", "fig-")
)


### Functions ======================================================================================
source(here("R/theme_black.R"))
get_metascore <- function(x) { 
  map_dbl(.x = paste0("https://www.imdb.com/title/", x, "/"), .f = function(y) {
    as.numeric(html_text(
      x = html_node(
        x = read_html(x = paste0(y, "criticreviews")), 
        css = "div.metascore"
      )              
    )) / 10
  })
}


### Define theme ===================================================================================
options(
  ggplot2.discrete.colour = scale_colour_viridis_d,
  ggplot2.discrete.fill = scale_fill_viridis_d,
  ggplot2.continuous.colour = scale_colour_viridis_c,
  ggplot2.continuous.fill = scale_fill_viridis_c
)
theme_set(
  theme_black(11, base_family = "xkcd") + 
    theme(
      plot.title.position = "plot", 
      plot.caption.position = "plot",
      plot.title = element_markdown(),
      plot.subtitle = element_markdown(face = "italic"),
      plot.caption = element_markdown(face = "italic", size = rel(0.6))
    )
)

fig_caption <- NULL # "&copy; Micka&euml;l '<i style='color:#21908CFF;'>Coeos</i>' Canouil"


### Import data ====================================================================================
movies_db <- map_df(
  .x = list.files(here("R"), "[0-9]{4}.R", full.names = TRUE), 
  .f = function(x) { 
    source(x)
    read_csv(
      file = here("data", gsub(".R$", ".csv", basename(x))), 
      col_types = cols(
        date_time = col_datetime(format = ""),
        room = col_double(),
        theatre = col_character(),
        imdb_id = col_character()
      )
    )
  }
) %>% 
  mutate(
    month = as.character(month(date_time, label = TRUE, abbr = FALSE)),
    year = year(date_time)
  )

ratings_db <- read_csv(
  file = here("data", "ratings.csv"), 
  locale = locale(encoding = "Windows-1252"), 
  col_types = cols(
    Const = col_character(),
    `Your Rating` = col_double(),
    `Date Rated` = col_date(format = ""),
    Title = col_character(),
    URL = col_character(),
    `Title Type` = col_character(),
    `IMDb Rating` = col_double(),
    `Runtime (mins)` = col_double(),
    Year = col_double(),
    Genres = col_character(),
    `Num Votes` = col_double(),
    `Release Date` = col_date(format = ""),
    Directors = col_character()
  )
) %>%
  rename_with(~ gsub("[()]", "", gsub(" ", "_", tolower(.x)))) %>% 
  mutate(
    genres = tolower(genres),
    month_rated = month(date_rated, label = TRUE, abbr = FALSE),
    year_rated = year(date_rated)
  )

if (file.exists(here("data", "ratings_ms.csv"))) {
  read_csv(
    file = here("data", "ratings_ms.csv"), 
    col_types = cols(
      const = col_character(),
      your_rating = col_double(),
      date_rated = col_date(format = ""),
      title = col_character(),
      url = col_character(),
      title_type = col_character(),
      imdb_rating = col_double(),
      runtime_mins = col_double(),
      year = col_double(),
      genres = col_character(),
      num_votes = col_double(),
      release_date = col_date(format = ""),
      directors = col_character(),
      month_rated = col_character(),
      year_rated = col_double(),
      metascore_rating = col_double()
    )
  ) %>% 
    filter(date_rated < (today() - 100) | year < year(today())) %>% 
    (function(.data) {
      anti_join(x = ratings_db, y = .data, by = "const") %>% 
        mutate(metascore_rating = get_metascore(const)) %>% 
        bind_rows(.data)
    })() %>% 
    write_csv(here("data", "ratings_ms.csv"))
} else {
  ratings_db %>% 
    mutate(metascore_rating = get_metascore(const)) %>% 
    write_csv(here("data", "ratings_ms.csv"))
}

ratings_ms <- read_csv(
  file = here("data", "ratings_ms.csv"), 
  col_types = cols(
    const = col_character(),
    your_rating = col_double(),
    date_rated = col_date(format = ""),
    title = col_character(),
    url = col_character(),
    title_type = col_character(),
    imdb_rating = col_double(),
    runtime_mins = col_double(),
    year = col_double(),
    genres = col_character(),
    num_votes = col_double(),
    release_date = col_date(format = ""),
    directors = col_character(),
    month_rated = col_character(),
    year_rated = col_double(),
    metascore_rating = col_double()
  )
) %>% 
  mutate(in_theatres = as.integer(const %in% movies_db[["imdb_id"]]))
```

# Streak of Movies Seen in Theatres

## Per Year

```{r streak-year, fig.width = 16 / 2.54, fig.height = 24.7 / 2.54}
streak_data <- movies_db %>% 
  mutate(date = date(date_time)) %>% 
  complete(date = full_seq(c(date, today()), 1)) %>% 
  group_by(date) %>% 
  summarise(count = sum(!is.na(theatre)), .groups = "drop") %>% 
  mutate(
    year = year(date),
    month = month(date, label = TRUE, abbr = FALSE),
    month_num = month(date),
    wday = wday(date, label = TRUE, abbr = FALSE, week_start = 1),
    count2 = ifelse(count == 0, NA, count)
  ) %>% 
  group_by(year) %>% 
  mutate(
    week = isoweek(date),
    week = ifelse(week == 1 & month_num == 12, max(week) + 1, week)
  ) %>% 
  ungroup() %>% 
  mutate(week = factor(sprintf("%02d", week), ordered = TRUE))

week_month_breaks <- streak_data %>% 
  filter(year > 2013) %>% 
  group_by(month) %>% 
  filter(wday == "Monday") %>% 
  add_count(week) %>% 
  distinct(month, week, n) %>% 
  filter(n == max(n)) %>% 
  filter(as.numeric(week) == min(as.numeric(week))) %>% 
  arrange(month, week) %>% 
  ungroup()

p <- ggplot(data = streak_data, mapping = aes(x = week, y = fct_rev(wday))) +
  geom_tile(
    data = ~ filter(.x, month_num %% 2 == 0),
    show.legend = FALSE,
    colour = "white",
    fill = "white",
    alpha = 0
  ) +
  geom_tile(
    data = ~ filter(.x, month_num %% 2 == 1),
    show.legend = FALSE,
    colour = "white",
    fill = "white",
    alpha = 0.2
  ) +
  geom_tile(aes(fill = count), alpha = 0.3) +
  geom_tile(
    data = ~ filter(.x, between(date, ymd("2020-03-16"), ymd("2020-06-21"))),
    fill = "#21908CFF", 
    alpha = 0.3
  ) +
  geom_text(aes(label = count2), colour = "white", na.rm = TRUE, family = "xkcd", size = 2.5) +
  scale_x_discrete(
    expand = expansion(c(0, 0)), 
    breaks = week_month_breaks[["week"]],
    labels = week_month_breaks[["month"]], 
    guide = guide_axis(n.dodge = 2)
  ) +
  scale_y_discrete(expand = expansion(c(0, 0))) +
  scale_colour_viridis_c() +
  scale_fill_viridis_c() +
  facet_grid(rows = vars(year)) +
  theme(
    panel.grid = element_blank(), 
    legend.position = "none"
  ) +
  labs(
    title = glue("Streak of Movies Seen in Theatres ({sum(streak_data$count)})"),
    caption = fig_caption,
    colour = "Count",
    fill = "Count",
    x = NULL, # "Week Number",
    y = NULL # "Day"
  )

p
```

## It Happened on Tuesdays

```{r streak-year-tuesday, fig.width = 16 / 2.54, fig.height = 24.7 / 2.54}
ftest <- movies_db %>% 
  mutate(wday = wday(date(date_time), label = TRUE, abbr = FALSE, week_start = 1)) %>% 
  filter(between(year, 2014, 2019)) %>% 
  mutate(is_tuesday = ifelse(wday=="Tuesday", "Tuesday", "Other Days")) %>% 
  count(year, is_tuesday) %>% 
  mutate(is_2019 = ifelse(year==2019, "2019", "2014-2018")) %>% 
  group_by(is_2019, is_tuesday) %>% 
  summarise(n = mean(n), .groups = "drop") %>% 
  mutate(n = ceiling(n)) %>% 
  pivot_wider(names_from = "is_tuesday", values_from = "n") %>% 
  column_to_rownames("is_2019") %>% 
  fisher.test() %>% 
  tidy() %>% 
  mutate_if(is.numeric, signif, digits = 3) %>% 
  glue_data(
    "<i style='color:#21908CFF;'>2019's Tuesdays</i> <i>Vs.</i> <i style='color:#21908CFF;'>2014-2018's Tuesdays</i>: ",
    "<span style='color:firebrick2;'>OR = {estimate}</span>; ",
    "95% CI, {conf.low}-{conf.high}; <span style='color:firebrick2;'>P = {p.value}</span>",
    "<br>(<i>{method}</i>)"
  )
p +
  labs(subtitle = ftest) + 
  annotate("rect", xmin = -Inf, xmax = Inf, ymin = -Inf, ymax = 5.5, fill = "grey20", alpha = 0.5) +
  annotate("rect", xmin = -Inf, xmax = Inf, ymin = 6.5, ymax = Inf, fill = "grey20", alpha = 0.5) +
  annotate("rect", xmin = -Inf, xmax = Inf, ymin = 5.5, ymax = 6.5, colour = "firebrick2", fill = "transparent") +
  scale_y_discrete(
    expand = expansion(c(0, 0)),
    labels = function(x) ifelse(x == "Tuesday", "<span style='color:firebrick2;'>Tuesday</span>", x)
  ) +
  theme(axis.text.y = element_markdown(size = rel(0.8)))
```

## In One Day

```{r streak-day}
movies_db %>% 
  add_count(year, date(date_time)) %>% 
  filter(n == max(n)) %>% 
  mutate(
    wday = wday(date(date_time), label = TRUE, abbr = FALSE, week_start = 1),
    day = day(date(date_time)),
    month = month(date(date_time), label = TRUE, abbr = FALSE),
    nth = case_when(
      day %in% c(1, 21, 31) ~ "st",
      day %in% c(2, 22) ~ "nd",
      day %in% c(3, 23) ~ "rd",
      TRUE ~ "th"
    ),
    time = glue("{hour(date_time)}h{minute(date_time)}"),
    date = glue("{wday}, the {day}{nth} of {month}, {year(date(date_time))}"),
    theatre = glue("UGC {theatre}")
  ) %>% 
  select(date, theatre, time, room) %>% 
  gt(auto_align = "center") %>% 
  opt_all_caps(all_caps = TRUE) %>% 
  opt_row_striping()
```

## Number of Movies Seen in Theatres per Month

```{r base-radar}
data_radar <- movies_db %>% 
  mutate(month = map_if(.x = month, .p = ~ .x=="January", .f = ~ c(.x, "JD"))) %>% 
  unnest(cols = month) %>% 
  count(year, month, name = "count") %>% 
  complete(nesting(year), month, fill = list(count = 0)) %>% 
  mutate(
    year = factor(x = year, levels = c(setdiff(sort(unique(year)), "ALL"), "ALL")),
    month = factor(month, levels = c(locale()$date_names$mon, "JD")),
    month_integer = as.integer(month),
    count = as.numeric(count)
  ) %>% 
  arrange(year, month) %>% 
  drop_na()

grid_data <- tibble(
  major = pretty_breaks(5)(c(0, max(data_radar[["count"]], na.rm = TRUE))),
  minor = c(major[-length(major)] + diff(major)/2, NA)
) %>% 
  pivot_longer(cols = c("major", "minor"), names_to = "type", values_to = "yintercept") %>% 
  drop_na() %>% 
  mutate(size = c("major" = 0.4, "minor" = 0.2)[type])

radar_base <- ggplot(data = data_radar, mapping = aes(x = month_integer, y = count, group = year)) +
  labs(
    title = "Number of Movies Seen in Theatres",
    caption = fig_caption,
    colour = "Year",
    fill = "Year"
  ) +
  coord_polar(theta = "x") +
  theme(
    axis.text.y = element_blank(),
    axis.text.x = element_text(size = rel(0.85)),
    axis.title = element_blank(),
    axis.ticks = element_blank(),
    axis.line = element_blank(),
    panel.grid = element_blank(),
    panel.border = element_blank(),
    plot.caption = element_markdown(halign = 1),
    plot.title = element_markdown(hjust = 0.5),
    plot.subtitle = element_markdown(hjust = 0.5)
  ) +
  scale_y_continuous(
    expand = expansion(mult = c(0, 0.15)),
    limits = c(0, 20)
  ) +
  scale_x_continuous(
    breaks = seq_len(12),
    labels = locale()$date_names$mon,
    limits = c(1, 13),
    expand = c(0, 0)
  ) +
  scale_colour_viridis_d(begin = 0.4) +
  scale_fill_viridis_d(begin = 0.4) +
  geom_hline( # layer 1
    yintercept = grid_data[["yintercept"]], 
    size = grid_data[["size"]],
    colour = theme_get()$panel.grid$colour
  ) +
  geom_vline( # layer 2
    xintercept = seq_len(13),
    colour = theme_get()$panel.grid$colour,
    size = 0.2
  ) +
  geom_text( # layer 3
    data = tibble(
      y = c(0, rep(unique(filter(grid_data, type=="major")[["yintercept"]])[-1], times = 4)),
      x = as.integer(c(1, rep(c(1, 4, 7, 10), each = 4)))
    ),
    mapping = aes(x = x, y = y, label = y),
    colour = theme_get()$text$colour,
    size = 16 * 1/4,
    inherit.aes = FALSE,
    family = "xkcd"
  )
```

### "*Radar*"

```{r circular-path, fig.width = 5.4}
circular_path <- radar_base +
  geom_vline( # layer 5
    data = data.frame(month_integer = seq_len(13)),
    mapping = aes(xintercept = month_integer),
    colour = theme_get()$panel.grid$colour,
    size = 0.4,
    na.rm = TRUE
  ) +
  geom_path( # layer 6
    mapping = aes(colour = year),
    size = 1.5,
    na.rm = TRUE, 
    show.legend = FALSE
  ) +
  geom_point( # layer 7
    mapping = aes(fill = year, group = paste(year, month_integer)),
    na.rm = TRUE,
    shape = 21,
    size = 5,
    colour = theme_get()$text$colour
  )

if (params[["static"]]) {
  print(circular_path)
} else {
  animate(
    plot = circular_path +
      transition_reveal(along = month_integer, range = c(1L, 13L), keep_last = TRUE) +
      shadow_wake(wake_length = 1 / 3, wrap = TRUE), 
    width = 5.3 * 2.54,
    height = 4.7 * 2.54,
    units = "cm", 
    res = 120,
    bg = theme_get()$plot.background$colour,
    renderer = gifski_renderer()
  )
}
```

### "*Sonar*"

```{r radar-point, fig.width = 5.4}
radar_point <- radar_base +
  map(
    .x = seq(from = 0, to = 3, by = 1.5),
    major_grid = filter(.data = grid_data, type=="major"),
    .f = function(x, major_grid) { # layer 5-8
      major_grid[["count"]] <- major_grid[["yintercept"]] +
        x * unique(diff(major_grid[["yintercept"]]))
      geom_hline(
        data = major_grid,
        mapping = aes(yintercept = count),
        colour = theme_get()$panel.grid$colour,
        size = 0.4,
        na.rm = TRUE
      )
    }
  ) +
  geom_point( # layer 9
    mapping = aes(fill = year, group = paste(year, month_integer)),
    na.rm = TRUE,
    shape = 21,
    size = 4,
    colour = theme_get()$text$colour
  )

if (params[["static"]]) {
  print(radar_point)
} else {
  animate(
    plot = radar_point +
      transition_reveal(
        along = count, 
        range = c(0, max(grid_data[["yintercept"]]) * 1.25), 
        keep_last = TRUE
      ) +
      shadow_wake(wake_length = 1 / 3, wrap = TRUE), 
    width = 5.3 * 2.54,
    height = 4.7 * 2.54,
    units = "cm", 
    res = 120,
    bg = theme_get()$plot.background$colour,
    renderer = gifski_renderer()
  )
}
```

# Ratings

```{r ratings}
who_colours <- setNames(viridis_pal(begin = 0.5, direction = -1)(3), c("COEOS", "METASCORE", "IMDB USERS"))
text_legend <- glue_collapse(
  glue("<b style='color:{who_colours};'>{names(who_colours)}</b>"), 
  sep = ", ", 
  last = " and "
)
p_ratings <- ggplot(
  data = pivot_longer(
    data = ratings_ms, 
    cols = ends_with("rating"), 
    names_to = "who", 
    names_pattern = "(.*)_.*", 
    names_transform = list(
      who = ~ factor(
        x = toupper(gsub("your", "coeos", .x)), 
        levels = c("COEOS", "METASCORE", "IMDB"),
        labels = 1:3
      )
    ),
    values_to = "rating"
  ),
  mapping = aes(
    x = rating, 
    y = after_stat(count / tapply(count, group, sum)[group]),
    colour = who, 
    fill = who
  )
) +
  annotation_raster(
    raster = matrix(rep(viridis_pal(option = "plasma", alpha = 0.10)(50), each = 50), nrow = 50),
    xmin = -Inf, xmax = Inf, ymin = -Inf, ymax = Inf
  ) +
  geom_bar(
    position = position_dodge2(width = 0.90, preserve = "single"),
    na.rm = TRUE,
    colour = NA
  ) +
  geom_text(
    mapping = aes(label = after_stat(percent(count / tapply(count, group, sum)[group], suffix = " %", accuracy = 0.1))),
    stat = "count",
    position = position_dodge2(width = 0.90, preserve = "single"),
    family = "xkcd",
    angle = 90,
    size = 3,
    hjust = -0.1,
    vjust = 0.5,
    na.rm = TRUE,
    show.legend = FALSE
  ) +
  scale_x_binned(
    limits = c(0, 10),
    right = FALSE,
    labels = function(x) ifelse(x %in% 10, x, paste0(x, "+")),
    expand = c(0, 0)
  ) +
  scale_y_continuous(labels = percent_format(suffix = " %"), expand = expansion(c(0, 0.15))) +
  scale_colour_manual(values = unname(who_colours), labels = names(who_colours)) +
  scale_fill_manual(values = unname(who_colours), labels = names(who_colours)) +
  labs(
    x = "Rating", 
    y = "Percentage of Movies", 
    colour = NULL,
    fill = NULL,
    title = glue(
      'Distribution of Ratings ({glue_collapse(range(drop_na(select(ratings_ms, year_rated, ends_with("rating")))[["year_rated"]]), sep = "--")}; N = {comma(nrow(drop_na(select(ratings_ms, ends_with("rating")))))})'
    ),
    subtitle = text_legend,
    caption = fig_caption
  ) +
  theme(
    legend.position = "none",
    panel.grid.minor = element_blank()
  )

if (params[["static"]]) {
  print(p_ratings + aes(group = who))
} else {
  animate(
    plot = p_ratings + 
      aes(group = paste(who, year_rated, sep = "_")) +
      labs(
        title = 'Distribution of Ratings ({comma(nrow(drop_na(select(filter(ratings_ms, year_rated == closest_state), ends_with("rating")))))}) in {closest_state}',
        subtitle = "{text_legend}"
      ) +
      transition_states(year_rated, transition_length = 3, state_length = 6) +
      enter_fade() +
      exit_fade(),
    width = 6.3 * 2.54,
    height = 4.7 * 2.54,
    units = "cm",
    res = 120,
    bg = theme_get()$plot.background$colour,
    renderer = gifski_renderer()
  )
}
```


# R session information

```{r session-info, results = "markup"}
session_info()
```
